- name: Load merge a configuration to a device running Junos OS
  hosts: junos
  connection: local
  gather_facts: no
  tasks:
    - name: Checking NETCONF connectivity
      wait_for: host={{ ansible_host }} port=830  timeout=30
