---
- name: Reset App Nodes
  hosts: webservers
  tasks:
    - name: Remove webservers from Nagios
      file:
        path: /opt/nagios/etc/objects/web_servers.cfg
        state: absent
      delegate_to: monitor1
      run_once: yes
    - name: Restart Nagios
      shell: 'docker restart nagios4'
      delegate_to: monitor1
      run_once: yes
    - name: Shutdown Nginx
      service:
        name: nginx
        state: stopped
        enabled: no
    - name: Remove nginx
      yum:
        name: nginx
        state: absent
