  mgmt_interface:
    name: FastEthernet0/0
    ip_address: 10.100.100.10/24

  main_interfaces:
    - name: GigabitEthernet1/0
      description: Link to JuniperR1 - ge-0/0/0
      ip_address: 192.168.100.10/24
      metric: 1
    - name: GigabitEthernet2/0
      description: Link to Webserver 1
      ip_address: 192.168.201.1/24
      metric: 1
